services:
  module_debug:
    class: Drupal\Console\Command\Module\DebugCommand
    arguments: ['@console.configuration_manager', '@console.site', '@http_client']
    tags:
      - { name: console.command }
  module_download:
    class: Drupal\Console\Command\Module\DownloadCommand
    arguments: ['@console.drupal_api', '@http_client',  '@app.root', '@console.extension_manager', '@console.validator', '@console.site', '@console.configuration_manager', '@console.shell_process']
    tags:
      - { name: console.command }
  module_install:
      class: Drupal\Console\Command\Module\InstallCommand
      tags:
        - { name: console.command }
  module_path:
      class: Drupal\Console\Command\Module\PathCommand
      tags:
        - { name: console.command }
  module_update:
    class: Drupal\Console\Command\Module\UpdateCommand
    tags:
      - { name: console.command }
  module_uninstall:
    class: Drupal\Console\Command\Module\UninstallCommand
    tags:
      - { name: console.command }
